// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SampleCore.Entity
{
    public partial class Emp_Details
    {
        public int Employee_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Department { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public DateTime Date_Of_Birth { get; set; }
        public int? Emp_LocationID { get; set; }
        public int Age { get; set; }
        public string Qualification { get; set; }
        public string Password { get; set; }
        public string Retype_Password { get; set; }
        public bool Is_Deleted { get; set; }
        public DateTime Created_Time_Stamp { get; set; }
        public DateTime Updated_Time_Stamp { get; set; }

        public virtual Emp_Location Emp_Location { get; set; }
    }
}