// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SampleCore.Entity
{
    public partial class Emp_Location
    {
        public Emp_Location()
        {
            Emp_Details = new HashSet<Emp_Details>();
        }

        public int Emp_LocationID { get; set; }
        public string Location { get; set; }
        public bool Is_Deleted { get; set; }
        public DateTime Created_Time_Stamp { get; set; }
        public DateTime Updated_Time_Stamp { get; set; }

        public virtual ICollection<Emp_Details> Emp_Details { get; set; }
    }
}